<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Insert default admin users
        DB::table('admins')->insert([
            [
                'id' => 1,
                'name' => 'System Super Admin',
                'email' => 'sumonmti498@gmail.com',
                'username' => 'superadmin',
                'email_verified_at' => $now,
                'password' => Hash::make('123456'),
                'image' => null,
                'phone' => '+1-800-ADMIN-01',
                'phone_verified_at' => $now,
                'address' => '123 Admin Headquarters, Suite 1000, Admin City, AC 12345',
                'role' => 'super_admin',
                'permissions' => json_encode([
                    'manage_users', 'view_users', 'create_users', 'edit_users', 'delete_users', 'ban_users',
                    'manage_admins', 'view_admins', 'create_admins', 'edit_admins', 'delete_admins',
                    'manage_products', 'view_products', 'create_products', 'edit_products', 'delete_products', 'approve_products',
                    'manage_orders', 'view_orders', 'edit_orders', 'cancel_orders', 'refund_orders',
                    'manage_categories', 'view_categories', 'create_categories', 'edit_categories', 'delete_categories',
                    'manage_finances', 'view_finances', 'manage_withdrawals', 'approve_withdrawals', 'manage_commissions',
                    'view_reports', 'view_analytics', 'export_data',
                    'manage_settings', 'view_settings', 'edit_settings', 'manage_themes', 'manage_plugins',
                    'manage_support', 'view_tickets', 'respond_tickets', 'close_tickets',
                    'manage_marketing', 'send_emails', 'manage_promotions', 'manage_coupons',
                    'manage_content', 'edit_pages', 'manage_blog', 'manage_media',
                    'view_logs', 'manage_backups', 'clear_cache', 'manage_database'
                ]),
                'is_active' => true,
                'is_super_admin' => true,
                'balance' => 50000.00,
                'total_deposited' => 50000.00,
                'total_withdrawn' => 0.00,
                'total_transferred' => 0.00,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'last_login_at' => $now,
                'last_login_ip' => '127.0.0.1',
                'last_login_user_agent' => 'Mozilla/5.0 (System Super Admin)',
                'login_attempts' => 0,
                'locked_until' => null,
                'notes' => 'System Super Administrator - Full Access',
                'status' => 'active',
                'department' => 'administration',
                'designation' => 'Chief Technology Officer',
                'employee_id' => 'EMP0001',
                'date_of_birth' => '1985-01-01',
                'gender' => 'prefer_not_to_say',
                'emergency_contact' => 'Emergency Admin Contact',
                'emergency_phone' => '+1-800-EMERGENCY',
                'hire_date' => '2020-01-01',
                'salary' => 150000.00,
                'commission_rate' => 0,
                'preferences' => json_encode([
                    'email_notifications' => true,
                    'sms_notifications' => true,
                    'dashboard_layout' => 'advanced',
                    'items_per_page' => 50,
                    'date_format' => 'Y-m-d',
                    'time_format' => '24h',
                    'auto_logout' => 240
                ]),
                'session_id' => null,
                'session_created_at' => null,
                'last_activity_at' => $now,
                'password_changed_at' => $now,
                'must_change_password' => false,
                'api_access_enabled' => true,
                'api_rate_limit' => 10000,
                'country' => 'United States',
                'state' => 'California',
                'city' => 'San Francisco',
                'postal_code' => '94105',
                'timezone' => 'America/Los_Angeles',
                'language' => 'en',
                'theme_preference' => 'dark',
                'supervisor_id' => null,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Admin Manager',
                'email' => 'admin@admin.com',
                'username' => 'adminmanager',
                'email_verified_at' => $now,
                'password' => Hash::make('Admin@123'),
                'image' => null,
                'phone' => '+1-800-ADMIN-02',
                'phone_verified_at' => $now,
                'address' => '456 Management Street, Suite 500, Admin City, AC 12346',
                'role' => 'admin',
                'permissions' => json_encode([
                    'manage_users', 'view_users', 'edit_users',
                    'manage_products', 'view_products', 'approve_products',
                    'manage_orders', 'view_orders', 'edit_orders',
                    'view_reports', 'view_analytics',
                    'manage_support', 'view_tickets', 'respond_tickets',
                    'manage_categories', 'view_categories', 'create_categories',
                    'view_finances', 'manage_withdrawals'
                ]),
                'is_active' => true,
                'is_super_admin' => false,
                'balance' => 25000.00,
                'total_deposited' => 25000.00,
                'total_withdrawn' => 0.00,
                'total_transferred' => 0.00,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'last_login_at' => $now->subHours(2),
                'last_login_ip' => '192.168.1.100',
                'last_login_user_agent' => 'Mozilla/5.0 (Admin Manager)',
                'login_attempts' => 0,
                'locked_until' => null,
                'notes' => 'Primary Admin Manager - General Administration',
                'status' => 'active',
                'department' => 'administration',
                'designation' => 'Admin Manager',
                'employee_id' => 'EMP0002',
                'date_of_birth' => '1990-05-15',
                'gender' => 'male',
                'emergency_contact' => 'Jane Manager',
                'emergency_phone' => '+1-555-0102',
                'hire_date' => '2021-03-15',
                'salary' => 85000.00,
                'commission_rate' => 0.02,
                'preferences' => json_encode([
                    'email_notifications' => true,
                    'sms_notifications' => false,
                    'dashboard_layout' => 'default',
                    'items_per_page' => 25,
                    'date_format' => 'Y-m-d',
                    'time_format' => '12h',
                    'auto_logout' => 120
                ]),
                'session_id' => null,
                'session_created_at' => null,
                'last_activity_at' => $now->subHours(1),
                'password_changed_at' => $now->subDays(30),
                'must_change_password' => false,
                'api_access_enabled' => true,
                'api_rate_limit' => 5000,
                'country' => 'United States',
                'state' => 'New York',
                'city' => 'New York',
                'postal_code' => '10001',
                'timezone' => 'America/New_York',
                'language' => 'en',
                'theme_preference' => 'light',
                'supervisor_id' => 1,
                'remember_token' => null,
                'created_at' => $now->subDays(30),
                'updated_at' => $now->subHours(1),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Finance Manager',
                'email' => 'finance@admin.com',
                'username' => 'financemanager',
                'email_verified_at' => $now,
                'password' => Hash::make('Finance@123'),
                'image' => null,
                'phone' => '+1-800-FINANCE',
                'phone_verified_at' => $now,
                'address' => '789 Finance Boulevard, Suite 300, Finance City, FC 54321',
                'role' => 'finance',
                'permissions' => json_encode([
                    'manage_finances', 'view_finances', 'manage_withdrawals',
                    'approve_withdrawals', 'manage_commissions',
                    'view_reports', 'view_analytics', 'export_data',
                    'view_users', 'view_orders', 'view_products'
                ]),
                'is_active' => true,
                'is_super_admin' => false,
                'balance' => 15000.00,
                'total_deposited' => 15000.00,
                'total_withdrawn' => 0.00,
                'total_transferred' => 0.00,
                'two_factor_secret' => 'JBSWY3DPEHPK3PXP',
                'two_factor_recovery_codes' => json_encode(['12345', '67890', '11111', '22222', '33333']),
                'two_factor_confirmed_at' => $now->subDays(10),
                'last_login_at' => $now->subHours(4),
                'last_login_ip' => '192.168.1.101',
                'last_login_user_agent' => 'Mozilla/5.0 (Finance Manager)',
                'login_attempts' => 0,
                'locked_until' => null,
                'notes' => 'Finance Department Manager - Financial Operations',
                'status' => 'active',
                'department' => 'finance',
                'designation' => 'Finance Manager',
                'employee_id' => 'EMP0003',
                'date_of_birth' => '1988-08-22',
                'gender' => 'female',
                'emergency_contact' => 'John Finance',
                'emergency_phone' => '+1-555-0103',
                'hire_date' => '2020-09-01',
                'salary' => 95000.00,
                'commission_rate' => 0.015,
                'preferences' => json_encode([
                    'email_notifications' => true,
                    'sms_notifications' => true,
                    'dashboard_layout' => 'financial',
                    'items_per_page' => 30,
                    'date_format' => 'M d, Y',
                    'time_format' => '12h',
                    'auto_logout' => 90
                ]),
                'session_id' => null,
                'session_created_at' => null,
                'last_activity_at' => $now->subHours(3),
                'password_changed_at' => $now->subDays(60),
                'must_change_password' => false,
                'api_access_enabled' => true,
                'api_rate_limit' => 3000,
                'country' => 'United States',
                'state' => 'Texas',
                'city' => 'Dallas',
                'postal_code' => '75201',
                'timezone' => 'America/Chicago',
                'language' => 'en',
                'theme_preference' => 'light',
                'supervisor_id' => 1,
                'remember_token' => null,
                'created_at' => $now->subDays(60),
                'updated_at' => $now->subHours(3),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Support Manager',
                'email' => 'support@admin.com',
                'username' => 'supportmanager',
                'email_verified_at' => $now,
                'password' => Hash::make('Support@123'),
                'image' => null,
                'phone' => '+1-800-SUPPORT',
                'phone_verified_at' => $now,
                'address' => '321 Support Center, Suite 200, Support City, SC 67890',
                'role' => 'support',
                'permissions' => json_encode([
                    'manage_support', 'view_tickets', 'respond_tickets', 'close_tickets',
                    'view_users', 'edit_users',
                    'view_orders', 'edit_orders',
                    'view_products',
                    'view_reports'
                ]),
                'is_active' => true,
                'is_super_admin' => false,
                'balance' => 5000.00,
                'total_deposited' => 5000.00,
                'total_withdrawn' => 0.00,
                'total_transferred' => 0.00,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'last_login_at' => $now->subMinutes(30),
                'last_login_ip' => '192.168.1.102',
                'last_login_user_agent' => 'Mozilla/5.0 (Support Manager)',
                'login_attempts' => 0,
                'locked_until' => null,
                'notes' => 'Customer Support Manager - Support Operations',
                'status' => 'active',
                'department' => 'support',
                'designation' => 'Support Manager',
                'employee_id' => 'EMP0004',
                'date_of_birth' => '1992-12-10',
                'gender' => 'male',
                'emergency_contact' => 'Mary Support',
                'emergency_phone' => '+1-555-0104',
                'hire_date' => '2022-01-15',
                'salary' => 65000.00,
                'commission_rate' => 0.01,
                'preferences' => json_encode([
                    'email_notifications' => true,
                    'sms_notifications' => false,
                    'dashboard_layout' => 'support',
                    'items_per_page' => 20,
                    'date_format' => 'Y-m-d',
                    'time_format' => '24h',
                    'auto_logout' => 60
                ]),
                'session_id' => null,
                'session_created_at' => null,
                'last_activity_at' => $now->subMinutes(15),
                'password_changed_at' => $now->subDays(90),
                'must_change_password' => false,
                'api_access_enabled' => false,
                'api_rate_limit' => 1000,
                'country' => 'United States',
                'state' => 'Florida',
                'city' => 'Miami',
                'postal_code' => '33101',
                'timezone' => 'America/New_York',
                'language' => 'en',
                'theme_preference' => 'auto',
                'supervisor_id' => 2,
                'remember_token' => null,
                'created_at' => $now->subDays(90),
                'updated_at' => $now->subMinutes(15),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Marketing Manager',
                'email' => 'marketing@admin.com',
                'username' => 'marketingmanager',
                'email_verified_at' => $now,
                'password' => Hash::make('Marketing@123'),
                'image' => null,
                'phone' => '+1-800-MARKETING',
                'phone_verified_at' => $now,
                'address' => '654 Marketing Avenue, Suite 400, Marketing City, MC 13579',
                'role' => 'marketing',
                'permissions' => json_encode([
                    'manage_marketing', 'send_emails', 'manage_promotions', 'manage_coupons',
                    'view_reports', 'view_analytics',
                    'view_users', 'view_products', 'view_orders',
                    'manage_content', 'edit_pages', 'manage_blog'
                ]),
                'is_active' => true,
                'is_super_admin' => false,
                'balance' => 8000.00,
                'total_deposited' => 8000.00,
                'total_withdrawn' => 0.00,
                'total_transferred' => 0.00,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'last_login_at' => $now->subHours(6),
                'last_login_ip' => '192.168.1.103',
                'last_login_user_agent' => 'Mozilla/5.0 (Marketing Manager)',
                'login_attempts' => 0,
                'locked_until' => null,
                'notes' => 'Marketing Department Manager - Promotional Campaigns',
                'status' => 'active',
                'department' => 'marketing',
                'designation' => 'Marketing Manager',
                'employee_id' => 'EMP0005',
                'date_of_birth' => '1987-04-18',
                'gender' => 'female',
                'emergency_contact' => 'Bob Marketing',
                'emergency_phone' => '+1-555-0105',
                'hire_date' => '2021-06-01',
                'salary' => 75000.00,
                'commission_rate' => 0.025,
                'preferences' => json_encode([
                    'email_notifications' => true,
                    'sms_notifications' => true,
                    'dashboard_layout' => 'marketing',
                    'items_per_page' => 25,
                    'date_format' => 'M d, Y',
                    'time_format' => '12h',
                    'auto_logout' => 120
                ]),
                'session_id' => null,
                'session_created_at' => null,
                'last_activity_at' => $now->subHours(5),
                'password_changed_at' => $now->subDays(45),
                'must_change_password' => false,
                'api_access_enabled' => true,
                'api_rate_limit' => 2000,
                'country' => 'United States',
                'state' => 'Illinois',
                'city' => 'Chicago',
                'postal_code' => '60601',
                'timezone' => 'America/Chicago',
                'language' => 'en',
                'theme_preference' => 'light',
                'supervisor_id' => 2,
                'remember_token' => null,
                'created_at' => $now->subDays(45),
                'updated_at' => $now->subHours(5),
                'deleted_at' => null,
            ]
        ]);

        // Reset the auto-increment to continue from ID 6
        DB::statement('ALTER TABLE admins AUTO_INCREMENT = 6');

        $this->command->info('✅ Default admin users created successfully!');
        $this->command->info('📧 Admin login credentials:');
        $this->command->info('Super Admin: superadmin@admin.com / SuperAdmin@123');
        $this->command->info('Admin Manager: admin@admin.com / Admin@123');
        $this->command->info('Finance Manager: finance@admin.com / Finance@123');
        $this->command->info('Support Manager: support@admin.com / Support@123');
        $this->command->info('Marketing Manager: marketing@admin.com / Marketing@123');
    }
}
